apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubys-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:                    # ← source tekil değil, çoğul
    - repoURL: https://github.com/yasinsunmaz/ubys-core-deployments.git
      targetRevision: HEAD
      path: projects          # ← önce project'ler
    - repoURL: https://github.com/yasinsunmaz/ubys-core-deployments.git
      targetRevision: HEAD
      path: appsets           # ← sonra appset'ler
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
