apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ubys-staging

# CI pipeline bu satırı günceller: bump-image.sh
images:
  - name: harbor.ikc.edu.tr/ubys-core-web-app/ubys-core-web-app
    newTag: "1.0.1"

configMapGenerator:
  - name: ubys-core-web-app-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - API_BASE_URL=http://ubys-core-web-app.ubys-staging.svc.cluster.local
      - LOG_LEVEL=warn

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ubys-core-web-app
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: ubys-core-web-app

resources:
  - ../../base  
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - secret.yaml

commonLabels:
  env: staging
