apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ubys-dev

bases:
  - ../../base

# CI pipeline bu satırı günceller: bump-image.sh
images:
  - name: harbor.example.com/ubys/student-portal
    newTag: "dev-abc1234"

configMapGenerator:
  - name: ubys-student-portal-config
    behavior: merge
    literals:
      - APP_ENV=dev
      - API_BASE_URL=http://ubys-student-portal.ubys-dev.svc.cluster.local
      - LOG_LEVEL=debug

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ubys-student-portal
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: ubys-student-portal

resources:
  - ingress.yaml

commonLabels:
  env: dev
