apiVersion: v1
kind: Service
metadata:
  name: ubys-notification-service
  labels:
    app: ubys-notification-service
spec:
  selector:
    app: ubys-notification-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
