apiVersion: v1
kind: Service
metadata:
  name: ubys-student-portal
  labels:
    app: ubys-student-portal
spec:
  selector:
    app: ubys-student-portal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
