apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: ubys-core-web-app
  app.kubernetes.io/part-of: ubys
  app.kubernetes.io/managed-by: argocd
