apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ubys-core-web-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/yasinsunmaz/ubys-core-deployments.git
        revision: HEAD
        directories:
          - path: apps/ubys-core-web-app/overlays/*

  template:
    metadata:
      name: "ubys-core-web-app-{{path.basename}}"
      labels:
        app: ubys-core-web-app
        env: "{{path.basename}}"

    spec:
      project: "default"

      source:
        repoURL: https://github.com/yasinsunmaz/ubys-core-deployments.git
        targetRevision: HEAD
        path: "{{path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "ubys-{{path.basename}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        # ignoreDifferences:
        #   - group: ""
        #     kind: Secret      

      revisionHistoryLimit: 5